global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['flex-gateway:8090']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  - job_name: 'postgres-mcp'
    static_configs:
      - targets: ['postgres-mcp:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'assets-mcp'
    static_configs:
      - targets: ['assets-mcp:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'notification-mcp'
    static_configs:
      - targets: ['notification-mcp:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'mule-broker'
    static_configs:
      - targets: ['mule-broker:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
